#ifndef APP_TYPES_H
#define APP_TYPES_H

enum app_mode {
	APP_MODE_NORMAL,
	APP_MODE_CONFIG,
	APP_MODE_DIAGNOSTIC,
};

enum app_runtime_state {
	APP_STATE_BOOT = 0,
	APP_STATE_IDLE,
	APP_STATE_MEASURING,
	APP_STATE_REPORTING,
	APP_STATE_ERROR,
};

enum app_wake_reason {
	APP_WAKE_REASON_NONE = 0,
	APP_WAKE_REASON_BOOT,
	APP_WAKE_REASON_SHAKE,
	APP_WAKE_REASON_PERIODIC,
	APP_WAKE_REASON_NFC,
	APP_WAKE_REASON_BLE_COMMAND,
};

#endif