#ifndef APP_TYPES_H
#define APP_TYPES_H

enum app_mode {
	APP_MODE_NORMAL = 0x00,
	APP_MODE_CONFIG = 0x01,
	APP_MODE_DIAGNOSTIC = 0x02,
};

enum app_runtime_state {
	APP_STATE_BOOT = 0x00,
	APP_STATE_IDLE = 0x01,
	APP_STATE_MEASURING = 0x02,
	APP_STATE_REPORTING = 0x03,
	APP_STATE_ERROR = 0x04,
};

enum app_wake_reason {
	APP_WAKE_REASON_NONE = 0x00,
	APP_WAKE_REASON_BOOT = 0x01,
	APP_WAKE_REASON_SHAKE = 0x02,
	APP_WAKE_REASON_PERIODIC = 0x03,
	APP_WAKE_REASON_NFC = 0x04,
	APP_WAKE_REASON_BLE_COMMAND = 0x05,
};

enum app_error_code {
	APP_ERROR_NONE = 0x000,
};

#endif
